### PR TITLE
Add support for live videos

### PR DESCRIPTION
**Pull request by glennguy**
Using AFL Live Pass credentials and Ooyala API to stream live matches.
'Live Matches' category added to main menu showing current live streams
and upcoming games for the current round.

### CODE REVIEW

**Comment by glennguy** [comment]
Hey Andy

I've tried to keep things fairly neat and fitting with your script. Unfortunately getting the url for Kodi takes a few seconds so has to be done at the last moment, making it not that practical to use with the video class. 

I shoved all the Ooyala API functions into their own module as they're mostly in common with the NRL Digital Pass implementation and it helps me if I need to make any future changes, but please make or suggest some changes to how I've structured everything if you see fit. I'm a total dev noob so any feedback is welcome!

Have a look and let me know what you think! :)

Glenn

**Comment by andybotting** [comment]
This is amazing. Really love your work. I'm watching Richmond v GC right now. Shame the quality isn't better though.

Code looks really good, but I haven't had a good look through yet. Not quite sold on the listitem colours just yet - may have a play with that later.

I'm interested in whether or not it's feasible to maybe group the quality settings into one generic low,medium,high rather than have two, but only if it makes sense.

I see you've got a live nrl addon - would you like that added to the catchup tv au repo?

**Comment by andybotting** [comment]
I've found that having an incorrect password set generates a HTTP 400 when fetching the auth token. Have you seen this?

**Comment by glennguy** [comment]
Oh snap, I remember now that I was going to add the handling for bad logins, fixed in new PR. 

With the live video quality, check that its set to 'highest' quality as I incorrectly had it set to default only to 'high'. Not as good as the match replays but not too far off.

Are there more than just the 3 exposed quality settings for the match replays?
The extra granularity in the live streams might come in handy for getting a sweet spot with poor connections. Some of my family who have a slow connection have tested and have found most annoying that unlike video on demand, any lack of bandwidth will just cause large gaps in the stream and have missed a bunch of good moments in the game.  

The listitem colors aren't anything I'm greatly attached to, I just had the idea from seeing other add-ons. It's mainly to guide the user to which items are playable, but I guess having 'LIVE NOW' or similar should really do the job. Maybe an OK dialog box telling the user to check back for a 'live now' entry closer to the match starting time?

I'd be very happy to add the NRL addon to the repo.

**Comment by andybotting** [comment]
Thanks Glenn. I was doing some hacking yesterday, and I think I worked around the incorrect password issue. I've reworked it so that the actual error message from the API is passed through as an exception instead. I think this is a cleaner, more flexible way to do it.

I've also made some changes to the colours too. I think your list idea is good, with the dummy options, but would love to find a better way of doing it. Works fine for now though.

I'm wondering if it might be a good idea to grant you access to our repo. Would love to catch you on IM (Hangouts works best for me). Want to shoot me an email with your details?

**Comment by glennguy** [comment]
Hey Andy, I sent an email the other night to your email listed on your
profile page. When you're not busy shoot me an IM and we can go from there.

Just tested the changes and like what I see. I'm still new at all this and
it's great to learn better ways to do things. One case that needs to be
handled with a valid login that has a lapsed/non existent subscription to
the service. I'll try and have a go at exception handling that as I've got
a Telstra ID with only an NRL sub on it to test.

Wrt list items - now that I look over the code I don't think I ended up
using the isdummy attribute at all for the dummy listings, setting the path
to something other than '' seemed to get the job done once switching over
to the setResolvedUrl method in the play module, so we can remove that
attribute from the video class.

**Pull request merged**
